name: Build and Deploy Application

on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Set up Docker environment
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: your-docker-registry/your-image-name:latest
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: your-docker-registry/your-image-name:latest
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: your-server-ip
          username: your-username
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker pull your-docker-registry/your-image-name:latest
            docker run -d --name your-container-name -p 80:80 your-docker-registry/your-image-name:latest

